active_language: eng

# intro_prompt:
#   welcome:
#     eng: Hi, I am Enhanced Med-Bot. Your over all healthcare buddy
#     fil: Magandang araw, Ako si Enhanced Med-Bot. Ang inyong kaibigan sa pagkuha nang vital signs measurements.
#   proceed:
#     eng: To proceed please scan your qrcode
#     fil: Para makakuha nang vital signs measurement, maaaring i-scan ang inyong qrcode.

# scan_prompt:
#   success: 
#     eng: Welcome, {}
#     fil: Mabuhay, {}
#   fail_qrcode:
#     eng: Wrong qrcode
#     fil: Mali ang iyong qrcode 
#   fail_credentials:
#     eng: Credentials do not match
#     fil: Hindi tugma sa iyong credentials

# sanitizing_prompt:
#   position:
#     eng: Please put your hand in front of the sanitizer
#     fil: Maaaring ilagay ang inyong kamay sa harap nang sanitizer
#   too_far:
#     eng: Your hand is too far
#     fil: Malayo ang iyong kamay
#   too_close:
#     eng: Your hand is too close
#     fil: Malapit ang inyong kamay
#   correct_position:
#     eng: Please keep your hands stay still. Now starting sanitizer
#     fil: Panatilihin ang mga kamay at magsisimula nang mag sanitize
#   success:
#     eng: Sanitizing complete. Proceeding to vital signs measurement
#     fil: tapos na ang sanitation. Magpatuloy na sa pagkuha nang vital signs
  
# arm_prompt:
#   position:
#     eng: Proceeding to vital signs measurement. Please position your arm properly
#     fil: Maaaring ilagay ang inyong braso nang maayos
#   rest:
#     eng: Please rest your arm correctly
#     fil: Maaaring ipahinga ang inyong braso nang tama
#   success:
#     eng: Your arm was detected
#     fil: Natukoy ang iyong braso
#   fail:
#     eng: Your arm is not detected
#     fil: Hindi matukoy ang iyong braso

# finger_prompt:
#   position:
#     eng: Please insert your finger on the oximeter
#     fil: Maaaring ilagay ang inyong daliri sa oximeter
#   success:
#     eng: Locking Oximeter, please do not remove your finger
#     fil: Isasarado na ang oximeter, pakiusap huwag alisin ang iyong daliri
#   fail:
#     eng: Finger not detected
#     fil: Hindi matukoy ang iyong daliri

# vital_signs_measurement:
#   getting_bp:
#     eng: Please stay still. Now getting your Blood Pressure and Pulse rate
#     fil: Manatili lamang, Ngayon ay kukunin na ang iyong Blood Pressure at Pulse rate
#   getting_temp:
#     eng: Now getting you temperature
#     fil: Ngayon ay kukunin na ang iyong temperatura
#   getting_os:
#     eng: Please stay still. Now getting your oxygen saturation
#     fil: Manatili lamang, Ngayon ay kukunin na ang iyong oxygen saturation
#   success:
#     eng: Vital signs measurement has completed
#     fil: tapos na ang pagkuha nang iyong vital signs measurement

results_prompt:
  prompt:
    eng: Here are your vital signs measurement
    fil: Narito ang iyong vital signs measurement
  result_bp:
    eng: Your blood pressure is {} over {} mmhg and it is {}
    fil: Ang iyong blood pressure ay {} over {} mmhg at ito ay {}
  result_os:
    eng: Your oxygen saturation is {} percent and it is {}
    fil: Ang iyong oxygen saturation ay {} percent at ito ay {}
  result_temp:
    eng: Your temperature is {} celcius and it is {}
    fil: Ang iyong temperatura ay {} celcius at ito ay {}
  result_pr:
    eng: Your pulse rate is {} bpm and it is {}
    fil: Ang iyong pulse rate ay {} bpm at ito ay {}

# printing:
#   prompt:
#     eng: Do you want to print your vital signs measurement? Click the button to print your results.
#     fil: Gusto mo ba nang kopya nang iyong vital signs measurement? Maaaring pindutin ang button upang makakuha nang kopya nang resulta nang iyong vital signs

#   thank_you_voice:
#     eng: Well done on completing your vital sign check up! We genuinely thank you for choosing our Med-Bot and allowing us to assist you in monitoring your well-being.
#     fil: Tapos na ang pagkumpleto nang iyong vital sign check up! Kami ay nagpapasalamat sa iyong pagpili nang aming Med-Bot at pagpapahintulot sa amin na tulungan ka sa pagsubaybay sa iyong kagalingan.

text_labels:
  text1:
    eng: Get Started
    fil: Magsimula

  text2:
    eng: " If you don't have an account \n yet, feel free to register on \n our website or simply scan \n the QR Code we've got right \n here for you."
    fil: "Kung wala ka pang account,\nmagrehistro sa aming website \n o i-scan ang QR Code dito."

  text3:
    eng: "Place your hands near the \nright arm of the Enhanced \nMed-Bot, and we'll get this \nsanitation started."
    fil: "Ilagay ang iyong kamay \nmalapit sa kanang braso \nnang Med-Bot upang \nmagsimula ang sanitasyon."

  text4:
    eng: "Well done on completing your vital sign \ncheck up! We genuinely thank you for \nchoosing our Med-Bot and allowing us to \nassist you in monitoring your well-being."
    fil: "Tapos na ang pagkumpleto nang iyong vital \nsign check up! Kami ay nagpapasalamat sa \niyong pagpili nang aming Med-Bot at pagpa-\npahintulot sa amin na tulungan ka sa \npagsubaybay sa iyong kagalingan."


intro_recording:
  welcome_recording:
    eng: Records/Eng/welcome_eng_1.mp3
    fil: Records/Fil/welcome_fil_1.mp3
  proceed_recording:
    eng: Records/Eng/scan_eng_1.mp3
    fil: Records/Fil/scan_fil_1.mp3

scan_recording:
  success_recording: 
    eng: Records/Eng/success_welcome_eng_1.mp3
    fil: Records/Fil/mabuhay_fil_1.mp3
  fail_qrcode_recording:
    eng: Records/Eng/wrong_eng.mp3
    fil: Records/Fil/wrong_fil.mp3
  fail_credentials_recording:
    eng: Records/Eng/credentials_eng.mp3
    fil: Records/Fil/credentials_fil.mp3

sanitizing_recording:
  position_recording:
    eng: Records/Eng/sanitizing_prompt_eng.mp3
    fil: Records/Fil/sanitizing_prompt_fil_1.mp3
  too_far_recording:
    eng: Records/Eng/too_far.mp3
    fil: Records/Fil/malayo_kamay_1.mp3
  too_close_recording:
    eng: Records/Eng/too_close.mp3
    fil: Records/Fil/malapit_kamay_1.mp3
  correct_position_recording:
    eng: Records/Eng/correct_pos_sanitizer_eng.mp3
    fil: Records/Fil/correct_pos_fil_1.mp3
  success_recording:
    eng: Records/Eng/proceeding_vtal_meas_eng_1.mp3
    fil: Records/Fil/proceeding_vtal_meas_fil_1.mp3

arm_recording:
  position_recording:
    eng: Records/Eng/arm_pos_eng_1.mp3
    fil: Records/Fil/arm_pos_fil_1.mp3
  rest_recording:
    eng: Records/Eng/rest_correct_eng_1.mp3
    fil: Records/Fil/rest_arm_fil_1.mp3
  success_recording:
    eng: Records/Eng/arm_detected_eng_1.mp3
    fil: Records/Fil/arm_detected_fil_1.mp3
  fail_recording:
    eng: Records/Eng/arm_not_detected_eng_1.mp3
    fil: Records/Fil/arm_not_detected_fil_1.mp3

finger_recording:
  position_recording:
    eng: Records/Eng/insert_finger_eng_1.mp3
    fil: Records/Fil/insert_finger_fil_1.mp3
  success_recording:
    eng: Records/Eng/locking_oxi_eng_1.mp3
    fil: Records/Fil/locking_oxi_fil_1.mp3
  fail_recording:
    eng: Records/Eng/finger_not_detected_eng_1.mp3
    fil: Records/Fil/finger_not_detected_fil_1.mp3

vital_signs_measurement_recording:
  getting_bp_recording:
    eng: Records/Eng/getting_bp_and_pr_eng_1.mp3
    fil: Records/Fil/getting_bp_and_pr_fil_1.mp3
  getting_temp_recording:
    eng: Records/Eng/getting_temp_eng_1.mp3
    fil: Records/Fil/getting_temp_fil_1.mp3
  getting_os_recording:
    eng: Records/Eng/getting_oxy_eng_1.mp3
    fil: Records/Fil/getting_oxy_fil_1.mp3
  success_recording:
    eng: Records/Eng/complete_vsigns_eng_1.mp3
    fil: Records/Fil/complet_vsigns_fil_1.mp3

results_recording:
  prompt_recording:
    eng: Records/Eng/vital_signs_measures_eng_1.mp3
    fil: Records/Fil/vital_signs_measure_fil_1.mp3
  result_bp_recording:
    eng: Records/Eng/blood_pressure_eng_1.mp3
    fil: Records/Fil/blood_pressure_fil_1.mp3
  over: Records/Uni/over_1.mp3
  mmhg: Records/Uni/mmhg_1.mp3
  bp_rating_result:
    eng: Records/Uni/and_it_is_1.mp3
    fil: Records/Uni/at_ito_ay_1.mp3

  result_os_recording:
    eng: Records/Eng/oxygen_is_1.mp3
    fil: Records/Fil/oxygen_fil_1.mp3
  percent: Records/Uni/percent_1.mp3
  os_rating_result:
    eng: Records/Uni/and_it_is_1.mp3
    fil: Records/Uni/at_ito_ay_1.mp3

  result_temp_recording:
    eng: Records/Eng/temp_is_1.mp3
    fil: Records/Fil/temp_fil_1.mp3
  celcius: Records/Uni/celcius_1.mp3
  temp_rating_result:
    eng: Records/Uni/and_it_is_1.mp3
    fil: Records/Uni/at_ito_ay_1.mp3

  result_pr_recording:
    eng: Records/Eng/pulse_rate_is_1.mp3
    fil: Records/Fil/pulse_rate_fil_1.mp3
  bpm: Records/Uni/bpm_1.mp3
  pr_rating_result:
    eng: Records/Uni/and_it_is_1.mp3
    fil: Records/Uni/at_ito_ay_1.mp3

printing_recording:
  print_recording:
    eng: Records/Eng/print_results_eng_1.mp3
    fil: Records/Fil/print_results_fil_1.mp3

  thank_you_voice_recording:
    eng: Records/Eng/thank_you_eng_1.mp3
    fil: Records/Fil/thank_you_fil_1.mp3